server:
  port: 8080

spring:
  application:
    name: moodjournal-backend
  datasource:
    url: jdbc:h2:mem:moodjournal;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
